options:

  source:
    type: string
    default: 'latest'
    description: 'Source of the strongswan installation'

  ip_forward:
    type: boolean
    default: True
    description: "IPv4 traffic forwarding" 

  ip6_forward:
    type: boolean
    default: False
    description: "IPv6 traffic forwarding."

  ike_version:
    type: int
    default:  2
    description: "IKE Version"

  authentication_method:
    type: string
    default: "secret"
    description: "Method of IPsec peer authentication"

  ipsec_protocol:
    type: string
    default: "esp"
    description: "IPsec protocol"

  virtual_ip_enabled:
    type: boolean
    default: True
    description: "Virtual IP"

  virtual_ip_subnet:
    type: string
    default: '10.50.9.0/24'
    description: 'Virtual IP subnet'

  private_subnets:
    type: string
    default: '10.10.10.0/24,'
    description: 'Comma seperated list of internal subnets we are providing access to'

  public_network:
    type: boolean
    default: True
    description: 'Will the security gateway provide access to the rest of the internet?'

  # do actions need ssh juju?
  allow_ssh:
    type: boolean
    default: True
    description: 'Will we allow ssh to the machine, turn this off after the machine has been set up.'

  

  # this is a major work in progress....
  # vpn_type:
  #   type: int
  #   default: 1
  #   description: "the default vpn type is rw--internal-"

  # specify where to build the source
  # source
  #   type: 'string'
  #   



