options:
  source:
    type: string
    default: 'archives'
    description: 'Source of the strongswan installation'
  config_options:
    type: string
    default: ''
    description: 'Comma seperated list of configuration parameters when compiling.'
  ip_forward:
    type: boolean
    default: True
    description: "IPv4 and IPv6 traffic forwarding, for security gateways (non host-host vpns)" 
  auth_method:
    type: string
    default: 'rsa' 
    description: "Method of IPsec peer authentication"
    enum: [rsa,x509,psk,secret]
  ipsec_protocol:
    type: string
    default: "esp" # todo enumeration of valid values
    description: "IPsec protocol"
    enum: [ah,esp]
  private_subnets:
    type: string
    default: ''
    description: 'Comma seperated list of internal subnets we are providing access to'
  public_network:
    type: boolean
    default: True
    description: 'Will the security gateway provide access to the rest of the internet?'