options:

  ip_forward:
    type: boolean
    default: True
    description: "IPv4 traffic forwarding"

  ip6_forward:
    type: boolean
    default: False
    description: "IPv6 traffic forwarding."

  ike_version:
    type: int
    default:  2
    description: "IKE Version"

  authentication_method:
    type: string
    default: "X.509"
    description: "Method of IPsec peer authentication"

  ipsec_protocol:
    type: string
    default: "esp"
    description: "IPsec protocol"

  virtual_ip:
    type: boolean
    default: True thi
    description: "Virtual IPs enabled"

  virtual_ip_range:
    type: string
    default: '10.50.9.0/24'
    description: 'Virtual IP address range'




  #
  vpn_type:
    type: int
    default:



