options:

  source:
    type: string
    default: 'archives'
    description: 'Source of the Strongswan installation'

  configuration:
    type: string
    default: ''
    description: 'Configuration options. See https://wiki.strongswan.org/projects/strongswan/wiki/Autoconf'

  verbose_logging:
    type: boolean
    default: false
    description: "Run hooks in debug mode."

  virtual_subnets:
    type: string
    default: "10.50.9.0/24,"
    description: "Comma separated list of virtual ip subnets."

  access_subnets:
    type: string
    default: ""
    description: "Comma separated list of access subnets."


  # auth_method:
  #   type: string
  #   default: 'rsa' 
  #   description: "Method of IPsec peer authentication"
