options:

  ip_forward:
    type: boolean
    default: True
    description: "IPv4 traffic forwarding"

  ip6_forward:
    type: boolean
    default: False
    description: "IPv6 traffic forwarding."

  ike_version:
    type: int
    default:  2
    description: "IKE Version"

  authentication_method:
    type: string
    default: "X.509"
    description: "Method of IPsec peer authentication"

  ipsec_protocol:
    type: string
    default: "esp"
    description: "IPsec protocol"

  virtual_ip_enabled:
    type: boolean
    default: True
    description: "Virtual IP"

  virtual_ip_subnet:
    type: string
    default: '10.50.9.0/24'
    description: 'Virtual IP subnet'

  internal_network_enabled:
    type: boolean
    default: False
    description: 'Will the security gateway provide access to an internal subnet?'

  internal_network_subnet:
    type: string
    default: ''
    description: 'What subnet will the security gateway provide access to'

  public_network_enabled:
    type: boolean
    default: True
    description: 'Will the security gateway '

  # this is a major work in progress....
  # vpn_type:
  #   type: int
  #   default: 1
  #   description: "the default vpn type is rw--internal-"



