options:
  source:
    type: string
    default: 'archives'
    description: 'Source of the strongswan installation'
  config_options:
    type: string
    default: ''
    description: 'Comma seperated list of configuration parameters when compiling.'
  auth_method:
    type: string
    default: 'rsa' 
    description: "Method of IPsec peer authentication"
  private_subnets:
    type: string
    default: ''
    description: 'Comma seperated list of internal subnets we are providing access to'
  public_network:
    type: boolean
    default: True
    description: 'Will the security gateway provide access to the rest of the internet?'
  verbose_logging:
    type: boolean
    default: false
    description: "Do you want to see a lot of logs, good for debugging?"