options:
  ip_forward:
    type: boolean
    default: True
    description: "IPv4 traffic forwarding"
  ip6_forward:
    type: boolean
    default: False # this fill eventually default to true
    description: "IPv6 traffic forwarding."

