options:

  source:
    type: string
    default: 'archives'
    description: 'Source of the strongswan installation'

  config_options:
    type: string
    default: ''
    description: 'Comma seperated list of configuration parameters when compiling.'

  ip_forward:
    type: boolean
    default: True
    description: "IPv4 traffic forwarding" 

  ip6_forward:
    type: boolean
    default: True
    description: "IPv6 traffic forwarding"

  ike_version:
    type: int
    default:  2
    description: "IKE Version"

  auth_method:
    type: string
    default: 'rsa'
    description: "Method of IPsec peer authentication"

  ipsec_protocol:
    type: string
    default: "esp"
    description: "IPsec protocol"

  virtual_ip_enabled:
    type: boolean
    default: True
    description: "Virtual IP"

  virtual_ip_subnet:
    type: string
    default: '10.50.9.0/24'
    description: 'Virtual IP subnet'

  private_subnets:
    type: string
    default: ''
    description: 'Comma seperated list of internal subnets we are providing access to'

  public_network:
    type: boolean
    default: True
    description: 'Will the security gateway provide access to the rest of the internet?'