#!/usr/bin/env python3

import strongswan.iptables as iptables
from strongswan.constants import CONFIG

def system_config():
	#iptables.filter()
	#iptables.nat()
	#iptables.save()
	pass

def ipsec_config():
	pass

if __name__ == "__main__":
	system_config()
	ipsec_config()
