#!/usr/bin/env python3

from strongswan.sysctl import(
	sysctl
)
from strongswan.iptables import(
	iptables
)
from charmhelpers.core import (
	hookenv
)

config = hookenv.config()



def _update():
	sysctl()
	iptables()

if __name__ == "__main__":
	hookenv.log("Running the configuration changed hook" , level=hookenv.INFO )
	_update()
	hookenv.log("Running the configuration changed hook" , level=hookenv.INFO )

