#!/usr/bin/env python

from strongswan.sysctl import(
	sysctl
)
from strongswan.iptables import(
	iptables_configure
)
from charmhelpers.core import (
	hookenv
)

class Strongswan:
	def __init__(self):
		self.config = hookenv.config()

	def update_config(self):
		sysctl(self.config)
		iptables_configure(self.config)




if __name__ == "__main__":
	hookenv.log("!!!!!!!!!!!!!!!!!! - Config Changed - !!!!!!!!!!!!!!!!!!!!")
	strongswan = Strongswan()
	strongswan.update_config()