#!/usr/bin/env python3

from charmhelpers.core import (
	hookenv
)
from strongswan.sysctl import(
	cp_sysctl_file,
	configure_sysctl
)
from strongswan.iptables import(
	configure_iptables
)
from strongswan.hosts import(
	cp_hosts_file
)
from strongswan.archive import (
	install_strongswan,
	install_pyOpenSSL
)
from strongswan.constants import (
	CONFIG
)


# If we are using x509 we will have to install other dependencies
if CONFIG.get("authentication_method") == 'x509':
	try:
		import OpenSSL
	except ImportError:
		install_pyOpenSSL()
	from strongswan.openssl import(
		create_ca_cert,
		create_host_cert
	)


# setup firewall
# sytem control
# make copies of important config files
def pre_install():
	bob
	configure_iptables()
	cp_sysctl_file()
	configure_sysctl()
	cp_hosts_file()
	
		

# install strongswan
def install():
	source = CONFIG.get("source")
	if source == 'distro':
		install_strongswan()
	elif source == 'upstream':
		pass
	else:
		hookenv.log("Install Source does not exist", level=hookenv.ERROR )
		raise
		#TODO raise an exception class


# some additional checks /etc/ipsec.d/
# create Root CA if we are using certs
def post_install():
	if CONFIG.get("authentication_method") == 'x509':
		create_ca_cert(CN="BeenswervingINC", L="Victoria", OU="Internet Security" )
		create_host_cert( 'server', CN="BeenswervingINC", L="Victoria", OU="Internet Security")



if __name__ == "__main__":
	pre_install()
	install()
	post_install()