#!/usr/bin/env python


from strongswan.apt import (
	ss_apt_pkgs,
	ss_apt_update
)
from strongswan.sysctl import(
	cp_sysctl_file
)
from charmhelpers.core import (
	hookenv
)
from charmhelpers.fetch import (
	apt_install
)

# global config 
config = hookenv.config()

def pre_install():
	cp_sysctl_file()
	# do we have the network
	# i've seen apt-get update fail because one of the archive servers is not responding...
		
def install():
	ss_apt_update()
	pkgs = ss_apt_pkgs(config)
	apt_install(packages=pkgs,fatal=True)


if __name__ == "__main__":
	hookenv.log("INFO:   Running the install hook")
	pre_install()
	install()
	hookenv.log("INFO:   Install hook has completed.")