#!/usr/bin/env python3

from charmhelpers.core import hookenv
from os.path import exists
from strongswan.openssl import create_root_cert
from strongswan.constants import (
	IPSEC_D_CACERTS,
	CA_CERT
)



if __name__ == '__main__':


	# if not ( exists( IPSEC_D_CACERTS + CA_CERT ) or
	# 	)
		 
	

