#!/usr/bin/env python3

from charmhelpers.core import hookenv
from os.path import exists
from strongswan.openssl import create_root_cert
from strongswan.util import get_action_params
from strongswan.constants import (
	IPSEC_D_CACERTS,
	CA_CERT
)



if __name__ == '__main__':

	# get the actions parameters
	params = get_action_params()


	# if overwrite is true or the certificate does not exist, create it.
	if params.get("overwrite") or not exists(IPSEC_D_CACERTS + CA_CERT) :
		create_root_cert( 
				params.get("subject"),
				params.get("lifetime"),
				params.get("keysize") 
		)
	else:
		pass 
		# return error
