#!/usr/bin/env python3
 
from charmhelpers.core import hookenv
from strongswan.openssl import create_host_cert


def _f1():
	hookenv.log("Action has been called!!!!")
	




if __name__ == '__main__':
	_f1()
	